### INDEX
GET http://localhost:3000/employees
### SHOW
GET http://localhost:3000/employees/1
### CREATE
POST http://localhost:3000/employees 
Content-Type: application/json 

{
  "first_name":"Steven",
  "last_name": "Metz",
  "email": "steven@test.com",
  "password":"password",
  "password_confirmation": "password",
  "image": "/lib/images"
}
### UPDATE
PATCH http://localhost:3000/employees/1 
Content-Type: application/json 

{
  "first_name":"Steven",
  "last_name": "Metz",
  "email": "steven@test.com",
  "image": "/lib/images"
}

### DESTROY
DELETE http://localhost:3000/employees/1 