@manager = eyJhbGciOiJIUzI1NiJ9.eyJlbXBsb3llZV9pZCI6MiwiZXhwIjoxNjczMTQzNDIzfQ.1kIr2GdRdK8BWMLm9m6rBOuoGOT5kqkaM3VEj4SKCFk
### INDEX
GET http://localhost:3000/employees.json
Authorization: Bearer {{manager}}
### SHOW
GET http://localhost:3000/employees/3.json
Authorization: Bearer {{manager}}

### CREATE
POST http://localhost:3000/employees.json 
Content-Type: application/json 

{
  "first_name":"Amanda",
  "last_name": "Amanda",
  "email": "amanda1@test.com",
  "password":"password",
  "password_confirmation": "password",
  "image": "/lib/images"
}
### UPDATE
PATCH http://localhost:3000/employees/11.json
Content-Type: application/json 

{
  "first_name":"Amanda",
  "last_name": "Hale",
  "email": "Amanda@test.com",
  "image": "/lib/images",
  "manager": true
}

### DESTROY
DELETE http://localhost:3000/employees/8.json

### LOGIN
POST http://localhost:3000/sessions.json 
Content-Type: application/json

{
  "email": "steven@test.com",
  "password": "password"
}

