@manager = eyJhbGciOiJIUzI1NiJ9.eyJlbXBsb3llZV9pZCI6MiwiZXhwIjoxNjc1MDk2MDE2fQ.EufRqCYyuO6eDAcBCfI2fQAN66y0K4RO84R9k7laXBg
### INDEX
GET http://localhost:3000/employees.json
Authorization: Bearer {{manager}}
### SHOW
GET http://localhost:3000/employees/3.json
Authorization: Bearer {{manager}}

### CREATE
POST http://localhost:3000/employees.json 
Content-Type: application/json 

{
  "first_name":"Amanda",
  "last_name": "hale",
  "email": "amandahal@test.com",
  "password":"thispassword",
  "password_confirmation": "thispassword",
  "image": "/lib/images"
}
### UPDATE
PATCH http://localhost:3000/employees/20.json
Content-Type: application/json 

{
  "first_name":"Amanda",
   "last_name": "Hale",
   "image": "/lib/images",
  "manager": true
}

### DESTROY
DELETE http://localhost:3000/employees/8.json

### LOGIN
POST http://localhost:3000/sessions.json 
Content-Type: application/json

{
  "email": "steve@example.com",
  "password": "password"
}

