@manager = eyJhbGciOiJIUzI1NiJ9.eyJlbXBsb3llZV9pZCI6MSwiZXhwIjoxNjc1NTI1MjE5fQ.vKNSCgiGssFQzX-nK0ITXZ0YXUbxEVqNJLRr7APn01U
### Index
GET http://localhost:3000/jobsites.json
Authorization: Bearer {{manager}}

### SHOW 
GET http://localhost:3000/jobsites/3.json 
Authorization: Bearer {{manager}}

### Create
Post http://localhost:3000/jobsites.json 
Content-Type: application/json
Authorization: Bearer {{manager}}

{
  "builder": "Espire",
  "location": "123 Main St, Menomonee Falls",
   "employee_id": 6
}

### Update
PATCH  http://localhost:3000/jobsites/6.json 
Content-Type: application/json
Authorization: Bearer {{manager}}


{
  "builder": "Tim O'Brien",
  "location": "1500 Main St, Menomonee Falls",
   "employee_id": 6,
   ""
}

### Destroy
DELETE  http://localhost:3000/jobsites/2.json 
Authorization: Bearer {{manager}}

### LOGIN
POST http://localhost:3000/sessions.json 
Content-Type: application/json

{
  "email": "joe@example.com",
  "password":"password"
}