
@manager = 
### Index
GET http://localhost:3000/punchins.json
### Show
GET http://localhost:3000/punchins/12.json
###
POST  http://localhost:3000/punchins.json
Content-Type: application/json
Authorization: Bearer {{manager}}

{
  "time_out": "10:45 pm"
}
### Update
PATCH http://localhost:3000/punchins/1.json
Content-Type: application/json
Authorization: Bearer {{manager}}

{
  "time_in": "10:05",
  "time_out": "11:45",
  "date": "2021-01-19"

  
}

### DESTROY
DELETE http://localhost:3000/punchins/2.json