@manager = eyJhbGciOiJIUzI1NiJ9.eyJlbXBsb3llZV9pZCI6MiwiZXhwIjoxNjcyOTUzODIxfQ.XhCBpQHwQU78dQrR4moFHfPy_0eKNSryso4kYF94YOk
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJlbXBsb3llZV9pZCI6NCwiZXhwIjoxNjcyODYxNjU0fQ.VXVE6ShP5MdrKfD28NM95nXWI3JrvUA0pZg1pV49arc
### INDEX
GET http://localhost:3000/todos
Authorization: Bearer {{manager}}

### SHOW
GET http://localhost:3000/todos/4
Authorization: Bearer {{manager}}


### CREATE
POST http://localhost:3000/todos
Content-Type: application/json
Authorization: Bearer {{manager}}


{
  "name": "Build gable E1E",
  "description": "Put Strong backs on gable\n apply backer to bottom of gable\n make sure gable is straight up and down.\n staple OSB to gable \n staple tyvek on \n build rake",
  "employee_id": 4
}
### UPDATE
PATCH  http://localhost:3000/todos/4
Content-Type: application/json
Authorization: Bearer {{manager}}

{
  "name": "do it again ",
  "description": "Put Strong backs on gableapply backer to bottom of gable make sure gable is straight up and down. staple OSB to gable staple tyvek on  build rake",
  "employee_id":4 ,
  "done": true
}
### DELETE
DELETE http://localhost:3000/todos/9
Authorization: Bearer {{manager}}
### LOGIN
POST http://localhost:3000/sessions.json 
Content-Type: application/json

{
  "email": "steven@test.com",
  "password": "password"
}
