### INDEX
GET http://localhost:3000/todos
### SHOW
GET http://localhost:3000/todos/1

### CREATE
POST http://localhost:3000/todos
Content-Type: application/json

{
  "name": "Build gable E1E",
  "description": "Put Strong backs on gable\n apply backer to bottom of gable\n make sure gable is straight up and down.\n staple OSB to gable \n staple tyvek on \n build rake",
  "employee_id": 1
}
### UPDATE
PATCH  http://localhost:3000/todos/2
Content-Type: application/json

{
  "name": "Build gable E1E",
  "description": "Put Strong backs on gableapply backer to bottom of gable make sure gable is straight up and down. staple OSB to gable staple tyvek on  build rake",
  "employee_id": 1,
  "done": false
}
### DELETE
DELETE http://localhost:3000/todos/2
